apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: discoverer
  labels:
    app: discoverer
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: ["*"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["stable.example.com"]
    resources: ["*"]
    verbs: ["get", "watch", "list"]
